name: var-genes-ro
channels:
  - bioconda
  - conda-forge
dependencies:
  - gawk = 5.1.0
  - seqkit = 0.16.1
  - exonerate = 2.4.0
  - jupyterlab = 3.0.16
  - biopython = 1.78
  - nbconvert = 5.6.0
  - ariba = 2.14.6
