name: notebook
channels:
  - bioconda
  - conda-forge
dependencies:
  - gawk = 5.1.0
  - seqkit = 0.16.1
  - exonerate = 2.4.0
  - jupyterlab = 3.0.16
  - biopython = 1.78
  - nbconvert = 5.6.0
  - ariba = 2.14.6
  # Required for bowtie2 (ariba dependency) to work
  # https://forum.biobakery.org/t/workflow-conda-install-bowtie-2-issue-bowtie2-align-s-error-while-loading-shared-libraries-libtbb-so-2/1831
  - tbb = 2020.2
